package interfaz;

import java.util.Vector;

import vistas.VistaListaComentariosUsuarioNoRegistrado;

public class Lista_Comentarios__Vista_Usuario_No_registrado_ extends VistaListaComentariosUsuarioNoRegistrado{
	public Ver_comentarios__Usuario_No_registrado_ _ver_comentarios__Usuario_No_registrado_;
	public Vector<Lista_Comentarios__Vista_Usuario_No_registrado__item> _item = new Vector<Lista_Comentarios__Vista_Usuario_No_registrado__item>();
}