package interfaz;

import java.util.Vector;

import vistas.VistaPublicacionesGustadasUsuarioPublico;

public class publicaciones_gustadas_usuario_publico extends VistaPublicacionesGustadasUsuarioPublico{
	public Ver_publicacciones_gustadas__Otro_usuario_ _ver_publicacciones_gustadas__Otro_usuario_;
	public Vector<publicaciones_gustadas_usuario_publico_item> _item = new Vector<publicaciones_gustadas_usuario_publico_item>();
}