package interfaz;

public class Ver_Perfil__2 extends Ver_tendencias {
	public Lista_Top_Comentarios__Usuario_No_Registrado__item _lista_Top_Comentarios__Usuario_No_Registrado_;
	public Lista_de_seguidores_item _lista_de_seguidores;
	public Lista_de_segidos_item _lista_de_segidos;
	public Lista_Publicaciones__Usuario_no_registrado__item _publicaciones__Usuario_no_registrado_;
	public top_usuarios_item _top_usuarios;
	public Resultado_usuarios_item _resultado_usuarios;
	public Ver_publicaci�n_ajena _ver_publicaci�n_ajena;
	public Publicaciones_hashtag_item _publicaciones_hashtag;
	public lista_usuarios_registrados_item _lista_usuarios_registrados;
	public Notificaciones__com�n_ _notificaciones__com�n_;
	public Ver_comentarios _ver_comentarios;
	public Lista_Comentarios__Vista_Usuario_No_registrado__item _lista_Comentarios__Vista_Usuario_No_registrado_;
	public Lista_Me_Gustas_Publicacion_item _lista_Me_Gustas_Publicacion;
	public Lista_resultado_item _lista_resultado;
	public Lista_denuncias_item _lista_denuncias;
	public Lista_Publicaciones__Administrador__item _lista_Publicaciones__Administrador_;
}