 package interfaz;

public class Ver_Perfil__2 extends Ver_perfil__1 {
	public Lista_Top_Comentarios_Usuario_No_Registrado_item _lista_Top_Comentarios__Usuario_No_Registrado_;
	public Lista_de_seguidores_item _lista_de_seguidores;
	public Lista_de_segidos_item _lista_de_segidos;
	public Lista_Publicaciones_Usuario_no_registrado_item _publicaciones__Usuario_no_registrado_;
	public Top_usuarios_item _top_usuarios;
	public Resultado_usuarios_item _resultado_usuarios;
	public Ver_publicacion_ajena _ver_publicacion_ajena;
	public Publicaciones_hashtag_item _publicaciones_hashtag;
	public Lista_usuarios_registrados_item _lista_usuarios_registrados;
	public Notificaciones_comun _notificaciones__comun_;
	public Ver_comentarios _ver_comentarios;
	public Lista_Comentarios_Vista_Usuario_No_registrado_item _lista_Comentarios__Vista_Usuario_No_registrado_;
	public Lista_Me_Gustas_Publicacion_item _lista_Me_Gustas_Publicacion;
	public Lista_resultado_item _lista_resultado;
	public Lista_denuncias_item _lista_denuncias;
	public Lista_Publicaciones_Administrador_item _lista_Publicaciones__Administrador_;
}